// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0HAgPIQPQpeX6QGlfU3Fr_8kk1jx7m08',
    appId: '1:988845762630:web:89d0ec11a32d8cb86d8247',
    messagingSenderId: '988845762630',
    projectId: 'smart-attendance-aac8e',
    authDomain: 'smart-attendance-aac8e.firebaseapp.com',
    storageBucket: 'smart-attendance-aac8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fL-NO3NCmwtf2ZL5MfZM4AgdbMwuTBw',
    appId: '1:988845762630:ios:1209c06a40f12f8a6d8247',
    messagingSenderId: '988845762630',
    projectId: 'smart-attendance-aac8e',
    storageBucket: 'smart-attendance-aac8e.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9fL-NO3NCmwtf2ZL5MfZM4AgdbMwuTBw',
    appId: '1:988845762630:ios:1209c06a40f12f8a6d8247',
    messagingSenderId: '988845762630',
    projectId: 'smart-attendance-aac8e',
    storageBucket: 'smart-attendance-aac8e.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendanceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0HAgPIQPQpeX6QGlfU3Fr_8kk1jx7m08',
    appId: '1:988845762630:web:11279129f9aab9bc6d8247',
    messagingSenderId: '988845762630',
    projectId: 'smart-attendance-aac8e',
    authDomain: 'smart-attendance-aac8e.firebaseapp.com',
    storageBucket: 'smart-attendance-aac8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeX-fuZND1Oz6huP_lOlVRuPz8As7mln8',
    appId: '1:988845762630:android:7e3cb2e7df3270bb6d8247',
    messagingSenderId: '988845762630',
    projectId: 'smart-attendance-aac8e',
    storageBucket: 'smart-attendance-aac8e.firebasestorage.app',
  );

}